version: 2

formats:
  - epub
  - pdf

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

python:
  install:
#    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
  system_packages: true

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py